### ISSUE TITLE
How to run squid?

### ISSUE THREAD

**Issue by hibissscus** [masutaka/heroku-buildpack-squid#1]
Hi, thank you for your squid buildpack

I installed your buildpack into heroku, then added necessary squid config as you described inside Wiki, but I have few questions:
1. When I install this buildpack it's automatically running squid after I did /app/.apt/usr/sbin/squid -f /app/.apt/etc/squid/squid.conf?
this is from log:
![image](https://user-images.githubusercontent.com/1389501/62502958-55257e80-b7f2-11e9-89e3-2928d5ddc520.png)
this is my instructions for squid config:
![image](https://user-images.githubusercontent.com/1389501/62503079-e268d300-b7f2-11e9-9088-6560666a2c6d.png)
2. Other question on which port this squid is running by default *3128*? And how from java app I can pointed on heroku at this squid buildpack (*which host*)?

Thank you for your time ^_^

**Comment by masutaka** [comment]
This is an Experimental buildpack.
See description on https://github.com/masutaka/heroku-buildpack-squid

Why do you want to use squid?

**Comment by hibissscus** [comment]
I want to crate a global proxy gate on heroku with a list of proxies configured with a help of squid and use this instance of heroku on some other heroku instances.

**Comment by masutaka** [comment]
I don't recommend using squid.

I recommend [QuotaGuard Static Add-on](https://elements.heroku.com/addons/quotaguardstatic) or [Proximo Add-on](https://elements.heroku.com/addons/proximo). You can also use [Private Spaces](https://www.heroku.com/private-spaces). However, the price is high.

If you still want to use squid, you should refer to [Buildpack API documentation](https://devcenter.heroku.com/articles/buildpack-api).

**Comment by hibissscus** [comment]
Thank you for recommendation. I will have a look at your suggestions.
